# Generated by Django 3.2.5 on 2021-07-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MtService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.TextField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('service_image', models.ImageField(upload_to='service/')),
            ],
            options={
                'verbose_name': 'My Service',
                'verbose_name_plural': 'My Services',
            },
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('project_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'MyProject',
                'verbose_name_plural': 'MyProjects',
            },
        ),
    ]
