# Generated by Django 3.2.5 on 2021-07-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MtService',
            new_name='MyService',
        ),
    ]
