# Generated by Django 3.2.5 on 2021-07-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_mtservice_myservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='project_image',
            field=models.ImageField(blank=True, upload_to='service/'),
        ),
    ]
